on: [push]

name: Run tests

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Restore the node modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Restore the dataset files 
      uses: actions/cache@v3
      with:
        path: '**/files/datasets'
        key: datasets-${{ hashFiles('**/files/download-datasets.sh') }}

    - name: Restore the feature set files 
      uses: actions/cache@v3
      with:
        path: '**/files/feature-sets'
        key: references-${{ hashFiles('**/files/download-feature-sets.sh') }}

    - name: Restore the reference files 
      uses: actions/cache@v3
      with:
        path: '**/files/references'
        key: references-${{ hashFiles('**/files/download-references.sh') }}

    - name: Restore the legacy files 
      uses: actions/cache@v3
      with:
        path: '**/files/legacy'
        key: references-${{ hashFiles('**/files/download-legacy.sh') }}

    - name: Install packages
      run: npm i --include-dev

    - name: Download datasets
      run: cd files && bash download-datasets.sh

    - name: Download references
      run: cd files && bash download-references.sh

    - name: Download feature sets
      run: cd files && bash download-feature-sets.sh

    - name: Download legacy 
      run: cd files && bash download-legacy.sh

    - name: Run tests
      run: npm run test
      timeout-minutes: 15
